print('| ============== Struct Tagihan =============== |')
print('| \t\tKosmetik\t\t ')
print('| Nama Barang : Sampo, Harga Barang : 5000 ')
print('| Nama Barang : Deodoran, Harga Barang : 15000 ') 
print('| \t\tBumbu\t\t\t ')
print('| Nama Barang : Masako, Harga Barang : 2000 ')
print('| Nama Barang : Uyah, Harga Barang : 2500 ') 
print('| \t\tMinuman\t\t ')
print('| Nama Barang : Cola-Cola, Harga Barang : 6000 ')
print('| Nama Barang : Sprite, Harga Barang : 4000 ') 